### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by AnthraxReaper** [KernCore91/-SC-Counter-Strike-1.6-Weapons-Project#1]
It's not working. I maybe installed it wrong. Can you all help me? Thank you!
![Screenshot 2021-01-14 045334](https://user-images.githubusercontent.com/77414028/104526653-efbbfb00-563d-11eb-8bc1-3275322cfce3.png)
![Screenshot 2021-01-14 045429](https://user-images.githubusercontent.com/77414028/104526655-f21e5500-563d-11eb-9fda-5f9e668d278b.png)

**Comment by KernCore91** [comment]
Check your `svencoop/logs/Angelscript`.  
I see nothing that could be the issue here.  
Maybe its failing somewhere, so could you post it here?

**Comment by AnthraxReaper** [comment]
Okey.
![image](https://user-images.githubusercontent.com/77414028/104751422-55200100-5790-11eb-94db-e8a4da586fef.png)

**Comment by KernCore91** [comment]
Can you try again with these new files? https://www.dropbox.com/s/6gb8tt3j7vkusyc/Sven-CS16_1-1.7z?dl=0

**Comment by AnthraxReaper** [comment]
Yes! It worked! Thank you.

**Comment by KernCore91** [comment]
Glad its working now, I shall update this soon.
