### ISSUE TITLE
Any way to make the money save with map changes?

### ISSUE THREAD

**Issue by danylopez123** [KernCore91/-SC-Counter-Strike-1.6-Weapons-Project#2]
Everytime a map changes, the money resets back to 0 and that can get a bit annoying having to be getting the money back.
Is it possible to make something so when a map changes, it keeps the money you were having?

**Comment by KernCore91** [comment]
https://github.com/KernCore91/-SC-Counter-Strike-1.6-Weapons-Project/blob/main/scripts/maps/cs16/BuyMenu.as#L500-L501

**Comment by danylopez123** [comment]
Ooh.. that explains it.. sorry.
Thanks for pointing that and fixing my thing, ill close this.
