### ISSUE TITLE
Possible to unload the plugin after being loaded?

### ISSUE THREAD

**Issue by danylopez123** [KernCore91/-SC-Counter-Strike-1.6-Weapons-Project#3]
I know this is too soon for me to post another issue but i've been trying to figure that out and i cant.

I know here is this thing of either you load the plugin for all the maps using the default_plugins.txt or load the plugin on specific maps you want by adding the map script but.. so far with what i had with this, this breaks a bit the uboa_rampage maps not being able to select certain weapons from the maps.

What i wanted to do is to see if i can add something for the uboa_rampage maps config files to disable the cs16 weapons but, it just did not worked.

That's why im asking if its possible to disable that plugin once its loaded from the default_plugins.txt for specific maps that breaks some other weapons.

If there is no way for that, then ill have to avoid loading those maps.

**Comment by KernCore91** [comment]
Certain weapons from uboa rampage have iPositions that conflict with the 1.6 plugin.  
When loading CS1.6 as a plugin, I do specific changes to the iPosition of each weapon [here](https://github.com/KernCore91/-SC-Counter-Strike-1.6-Weapons-Project/blob/main/scripts/maps/cs16/cs16_register.as#L10-L44) so they don't conflict with custom map weapons (if they're using 4 to 9).
What you could try doing is modifying the map's weapon iPositions so they don't conflict with the plugin anymore.

If you want to completely disable weapon registering in that map then you should add some code to ignore the map after this [line](https://github.com/KernCore91/-SC-Counter-Strike-1.6-Weapons-Project/blob/main/scripts/maps/cs16/cs16_register.as#L52): 
```cpp
if( string(g_Engine.mapname) == "uboa_rampage" )
    return;
```

**Comment by danylopez123** [comment]
Which file do i need to put that code?

**Comment by KernCore91** [comment]
After [this line](https://github.com/KernCore91/-SC-Counter-Strike-1.6-Weapons-Project/blob/main/scripts/maps/cs16/cs16_register.as#L52) in the cs16_register file

**Comment by danylopez123** [comment]
That did the trick, thanks!
Before i close this post, can you give me an example if i want to add more than 1 map? Because i have more maps that uses custom weapons and uboa_rampage its not the only one.

**Comment by KernCore91** [comment]
```cpp
if( string(g_Engine.mapname) == "uboa_rampage" || string(g_Engine.mapname) == "dis_beta" )
    return;
```
I used dis_beta as an example `|| string(g_Engine.mapname) == "dis_beta"` this part is the one that matters.

**Comment by danylopez123** [comment]
Alright, thanks for the example!
Now i can close this issue.
