### ISSUE TITLE
Expansion idea

### ISSUE THREAD

**Issue by Specter153** [KernCore91/-SC-Counter-Strike-1.6-Weapons-Project#4]
Hello this isn't really much of an issue as much as a project i have been messing around with. First off i your CS weapons pack is amazing and lately i have been adding some additional weapons in in what i like to call the Counter-Strike: Online Expansion Pack. The problem is that i have been having some issues:
1. I cannot figure out how to add a secondary fire to any of the weapon's weather it is a simple zoom function to a different function entirely without crashing.
2. I also cannot modify the reload animations without crashing either (this was mostly work on the shotguns)
3. Finally there are some weapons i cannot add like a rocket launcher or grenade launcher either without crashing the mod.
So if you could help me with these things that would be great. Also if you would like i can send you a copy of the mod if you want to try it out.

Thanks!

**Comment by KernCore91** [comment]
I am not interested in anything Counter-Strike Online related, as Misfire's servers already has a lot of them in their servers.  
Good Luck.
