### ISSUE TITLE
How do I disable buying?

### ISSUE THREAD

**Issue by chimz76** [KernCore91/-SC-Counter-Strike-1.6-Weapons-Project#5]
Hello and good day.

I want to know how I can disable the buy menu and buying entirely. I am trying to make a Counter-Strike campaign map and placing the weapons as I see fit. I am registering the weapons as map_scripts so I can't use the Server commands to limit them.

So is there a way for me to disable buying entirely?

**Comment by KernCore91** [comment]
You should make a custom register file to use with your map.  
That should give you complete freedom to modify what you want.

**Comment by chimz76** [comment]
As I don't do any programming, I had not dared to edit the files before lol. Fixed it, thank you!

For anyone else wondering what I did:
You can edit the value of `as_command cs16.bm_moneyperscore` and `as_command cs16.bm_startmoney` inside the script **BuyMenu.as**. Or just remove and change the various words used for buying.

If you don't want to edit the original files (so that they don't overwrite or get overwritten later) you can create a copy of **cs16_register.as** and **BuyMenu.as**. Open the register copy you made and edit the second like to open your new BuyMenu script. In my case I simply added "_nobuy" to both to differentiate and avoid any naming errors.


Call the register copy (in my case called "cs16_register_nobuy" inside your map cfg and you should be good.

**Comment by KernCore91** [comment]
You can follow this [guide](https://github.com/KernCore91/-SC-Insurgency-Weapons-Project/wiki/Creating-your-own-Register-File) I made for the ins2 weapons.  
It works almost exactly the same but you should modify it for the cs1.6 weapons.
